server.port=${PORT:8082}

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=Rm555999
spring.datasource.password=250403

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.indent-output=true

// Eu coloquei esse parâmetro para habilitar o uso do método PUT e DELETE no Spring Boot, pois por padrão ele não aceita esses métodos.
spring.mvc.hiddenmethod.filter.enabled=true